import { test } from "@playwright/test";

// Regenerated by `make docs-screenshots`, reusing this app's own smoke
// test rather than a separate screenshot harness — the docs standard
// (PORTFOLIO_PLAN_V3.md §9.4) so a screenshot can never silently go stale
// relative to the running app. Only the homepage: it needs no backend, so
// this stays runnable in CI without a live cohort.db/registry.
test("homepage", async ({ page }) => {
  await page.goto("/");
  await page.screenshot({ path: "../docs/assets/homepage-screenshot.png", fullPage: true });
});
